# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SalamiUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setToolTipDuration(0)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_ExperimentControls = QtWidgets.QGroupBox(self.tab)
        self.groupBox_ExperimentControls.setObjectName("groupBox_ExperimentControls")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_ExperimentControls)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spinBox_SampleHolderTilt = QtWidgets.QSpinBox(self.groupBox_ExperimentControls)
        self.spinBox_SampleHolderTilt.setObjectName("spinBox_SampleHolderTilt")
        self.gridLayout_3.addWidget(self.spinBox_SampleHolderTilt, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_ExperimentControls)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.checkBox_UseSenseAI = QtWidgets.QCheckBox(self.groupBox_ExperimentControls)
        self.checkBox_UseSenseAI.setObjectName("checkBox_UseSenseAI")
        self.gridLayout_3.addWidget(self.checkBox_UseSenseAI, 1, 0, 1, 2)
        self.pushButton_RunSetup = QtWidgets.QPushButton(self.groupBox_ExperimentControls)
        self.pushButton_RunSetup.setObjectName("pushButton_RunSetup")
        self.gridLayout_3.addWidget(self.pushButton_RunSetup, 2, 0, 1, 2)
        self.pushButton_RunExperiment = QtWidgets.QPushButton(self.groupBox_ExperimentControls)
        self.pushButton_RunExperiment.setObjectName("pushButton_RunExperiment")
        self.gridLayout_3.addWidget(self.pushButton_RunExperiment, 3, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_ExperimentControls, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Salami"))
        self.groupBox_ExperimentControls.setTitle(_translate("MainWindow", "Experiment Controls"))
        self.label.setText(_translate("MainWindow", "Sample Holder Tilt"))
        self.checkBox_UseSenseAI.setText(_translate("MainWindow", "Use SenseAI For Capture"))
        self.pushButton_RunSetup.setText(_translate("MainWindow", "Setup Experiment"))
        self.pushButton_RunExperiment.setText(_translate("MainWindow", "Run Experiment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Experiment"))
