# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SenseAIControlWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(473, 761)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_Reconstruct_control = QtWidgets.QGroupBox(Form)
        self.groupBox_Reconstruct_control.setObjectName("groupBox_Reconstruct_control")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_Reconstruct_control)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_Reconstruct = QtWidgets.QPushButton(self.groupBox_Reconstruct_control)
        self.pushButton_Reconstruct.setObjectName("pushButton_Reconstruct")
        self.gridLayout_3.addWidget(self.pushButton_Reconstruct, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_Reconstruct_control, 4, 0, 1, 1)
        self.label_SenseAI = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_SenseAI.setFont(font)
        self.label_SenseAI.setObjectName("label_SenseAI")
        self.gridLayout.addWidget(self.label_SenseAI, 0, 0, 1, 1)
        self.pushButton_init_scanGen = QtWidgets.QPushButton(Form)
        self.pushButton_init_scanGen.setObjectName("pushButton_init_scanGen")
        self.gridLayout.addWidget(self.pushButton_init_scanGen, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../util/resources/logos/senseAI.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.groupBox_ScanControl = QtWidgets.QGroupBox(Form)
        self.groupBox_ScanControl.setObjectName("groupBox_ScanControl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_ScanControl)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_AcquireImage = QtWidgets.QPushButton(self.groupBox_ScanControl)
        self.pushButton_AcquireImage.setObjectName("pushButton_AcquireImage")
        self.gridLayout_2.addWidget(self.pushButton_AcquireImage, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_ScanControl, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_Reconstruct_control.setTitle(_translate("Form", "Reconstruction Control"))
        self.pushButton_Reconstruct.setText(_translate("Form", "Reconstruct"))
        self.label_SenseAI.setText(_translate("Form", "SenseAI Control "))
        self.pushButton_init_scanGen.setText(_translate("Form", "Initialise Scan Generator"))
        self.groupBox_ScanControl.setTitle(_translate("Form", "Scan Control"))
        self.pushButton_AcquireImage.setText(_translate("Form", "Acquire Image"))
